ehowey/gatsby-theme-catalyst

starters/gatsby-starter-catalyst-basic/gatsby-config.js
starters/gatsby-starter-catalyst-blog/gatsby-config.js
starters/gatsby-starter-catalyst-core/gatsby-config.js
starters/gatsby-starter-catalyst-writer/gatsby-config.js
starters/gatsby-starter-catalyst-writer/sanity-studio/schemas/siteSettings.js
themes/gatsby-theme-catalyst-core/gatsby-config.js
themes/gatsby-theme-catalyst-core/src/utils/seo.js
themes/gatsby-theme-catalyst-core/src/utils/use-site-metadata.js
themes/gatsby-theme-catalyst-writer/src/gatsby-theme-catalyst-core/utils/seo.js
themes/gatsby-theme-catalyst-writer/src/gatsby-theme-catalyst-core/utils/use-site-metadata.js

- Removes "twitter" field from gatsby-config.js and instead finds it and parses it from the socialLinks array.

(feat) remove twitter config

---

README.md
starters/gatsby-starter-catalyst-basic/gatsby-config.js
starters/gatsby-starter-catalyst-blog/gatsby-config.js
starters/gatsby-starter-catalyst-core/gatsby-config.js
starters/gatsby-starter-catalyst-writer/gatsby-config.js
themes/gatsby-theme-catalyst-core/gatsby-node.js
themes/gatsby-theme-catalyst-core/src/utils/use-catalyst-config.js
themes/gatsby-theme-catalyst-footer/README.md
themes/gatsby-theme-catalyst-footer/src/gatsby-theme-catalyst-core/components/footer.js

- Implements `footerContentLocation` as a way to control the location of content in the footer, options are "left", "right" and "center".  Defaults to "left".

(feat) control footer content location

---

starters/gatsby-starter-catalyst-core/content/pages/index.mdx
themes/gatsby-theme-catalyst-core/gatsby-config.js
themes/gatsby-theme-catalyst-core/package.json
yarn.lock

Fixes #352 
Haven't worked with yarn workspaces before, so please let me know if there is something wrong.
Added a small example to the index page used by running `yarn develop:core`, let me know if you think it would be best to remove it or to add it somewhere else.

Add support for embeds using gatsby-mdx-embed

---

themes/gatsby-theme-catalyst-writer/src/gatsby-theme-catalyst-core/utils/use-site-metadata.js

- More robust query, should prevent build from failing with odd behaviour in SANITY

Updated query for siteMetadata, more robust

---

themes/gatsby-theme-catalyst-writer/src/components/home-contact.js
themes/gatsby-theme-catalyst-writer/src/components/home-hero.js
themes/gatsby-theme-catalyst-writer/src/components/home-logos.js
themes/gatsby-theme-catalyst-writer/src/components/home-work.js
themes/gatsby-theme-catalyst-writer/src/components/pages/bio-page.js
themes/gatsby-theme-catalyst-writer/src/components/pages/contact-page.js
themes/gatsby-theme-catalyst-writer/src/components/pages/home-page.js
themes/gatsby-theme-catalyst-writer/src/components/pages/work-page.js

- Better page queries using, more robust and should be more difficult to create problems due to inconsistencies in the database

(catalyst-writer): implement better queries

---

starters/gatsby-starter-catalyst-writer/gatsby-config.js

- Fixes https://github.com/ehowey/gatsby-theme-catalyst/issues/425

Updated gatsby-config

---

cypress/e2e/ally.test.js
cypress/e2e/navigation.test.js
cypress/e2e/smoke.js
cypress/e2e/smoke.test.js
starters/gatsby-starter-catalyst-basic/content/pages/index.mdx
starters/gatsby-starter-catalyst-basic/src/gatsby-theme-catalyst-core/theme.js
starters/gatsby-starter-catalyst-blog/content/pages/index.mdx
starters/gatsby-starter-catalyst-blog/src/gatsby-theme-catalyst-core/theme.js
starters/gatsby-starter-catalyst-core/content/pages/index.mdx
starters/gatsby-starter-catalyst-core/src/gatsby-theme-catalyst-core/theme.js

- Tests dark mode
- Tests navigation menu
- More robust tests, should be less likely to fail
Addresses: https://github.com/ehowey/gatsby-theme-catalyst/issues/379

(all): improved tests with cypress

---

themes/gatsby-theme-catalyst-core/gatsby-browser.js
themes/gatsby-theme-catalyst-core/package.json
themes/gatsby-theme-catalyst-core/src/components/layout.js
themes/gatsby-theme-catalyst-core/src/utils/normalize-css.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links.js
yarn.lock

- Adds a basic skip nav function following the https://www.gatsbyjs.org/blog/2020-02-10-accessible-client-side-routing-improvements/

(feat): Implement a skip nav function

---

cypress/e2e/ally.test.js
starters/gatsby-starter-catalyst-basic/src/gatsby-theme-catalyst-core/theme.js
starters/gatsby-starter-catalyst-blog/src/gatsby-theme-catalyst-core/theme.js
starters/gatsby-starter-catalyst-core/src/gatsby-theme-catalyst-core/theme.js
themes/gatsby-theme-catalyst-core/src/theme.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-color-button.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-color-button.js

- Fixes a bug due to initialColorMode being "default"

(fix): set initialColorModeName to "light"

---

.github/workflows/test-docs.yml
.github/workflows/test-themes.yml
cypress/e2e/docs.test.js
cypress/e2e/themes.test.js

- Adds a couple more tests for the themes and docs site

(all): add tests

---

www/content/docs/docs/gatsby-theme-catalyst-header-bigtop.mdx
www/content/docs/docs/gatsby-theme-catalyst-header-top.mdx
www/gatsby-config.js

(www): update docs for helium and big top

---

starters/gatsby-starter-catalyst-blog/package.json
starters/gatsby-starter-catalyst-core/package.json
starters/gatsby-starter-catalyst-helium/package.json
starters/gatsby-starter-catalyst-hydrogen/package.json
starters/gatsby-starter-catalyst-sanity/package.json
starters/gatsby-starter-catalyst/package.json
themes/gatsby-theme-catalyst-blog/package.json
themes/gatsby-theme-catalyst-core/package.json
themes/gatsby-theme-catalyst-footer/package.json
themes/gatsby-theme-catalyst-header-bigtop/package.json
themes/gatsby-theme-catalyst-header-side/package.json
themes/gatsby-theme-catalyst-header-top/package.json
themes/gatsby-theme-catalyst-helium/package.json
themes/gatsby-theme-catalyst-hydrogen/package.json
themes/gatsby-theme-catalyst-sanity/package.json
www/package.json
www/yarn.lock

- Revert Gatsby version
- Update yarn.lock to prevent error with `@theme-ui/prism` not installing correctly

(all): fix yarn.lock problem with theme-ui, revert Gatsby version

---

themes/gatsby-theme-catalyst-blog/gatsby-config.js

- bug fix to ensure right links are used for rss feed

(blog): Fix link for rss feed

---

starters/gatsby-starter-catalyst-helium/content/pages/about.mdx
starters/gatsby-starter-catalyst-helium/content/posts/what-to-do-when-things-go-wrong-during-a-rocket-launch.mdx
starters/gatsby-starter-catalyst-helium/content/posts/who-you-choose-to-go-to-space-says-a-lot-about-you.mdx
starters/gatsby-starter-catalyst-helium/src/gatsby-plugin-theme-ui/index.js
starters/gatsby-starter-catalyst-helium/src/gatsby-theme-catalyst-helium/components/hero.js
themes/gatsby-theme-catalyst-helium/src/components/post-list.js
themes/gatsby-theme-catalyst-helium/src/components/post.js
themes/gatsby-theme-catalyst-helium/src/gatsby-theme-catalyst-blog/components/queries/post-list-query.js
themes/gatsby-theme-catalyst-helium/src/gatsby-theme-catalyst-blog/components/queries/post-query.js
www/content/docs/docs/gatsby-theme-catalyst-helium.mdx

- improved styles and colors for the card components
- support for categories

(helium)  better styles and cards

---

starters/gatsby-starter-catalyst-helium/gatsby-config.js
starters/gatsby-starter-catalyst-helium/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-catalyst-header-bigtop/README.md
themes/gatsby-theme-catalyst-header-bigtop/src/components/header.js
www/content/docs/docs/gatsby-theme-catalyst-header-bigtop.mdx

- Fixes a bug with the header d/t static vs sticky header

Fix header-bigtop

---

themes/gatsby-theme-catalyst-helium/src/components/post-list.js

- minor visual tweaks to image sizes in the cards

(helium): more adjustments to the cards

---

www/gatsby-config.js

Fix the link to gatsby-config.js

---

starters/gatsby-starter-catalyst-blog/package.json
starters/gatsby-starter-catalyst-core/package.json
starters/gatsby-starter-catalyst-helium/package.json
starters/gatsby-starter-catalyst-hydrogen/package.json
starters/gatsby-starter-catalyst-sanity/package.json
starters/gatsby-starter-catalyst/package.json
themes/gatsby-theme-catalyst-blog/package.json
themes/gatsby-theme-catalyst-core/package.json
themes/gatsby-theme-catalyst-footer/package.json
themes/gatsby-theme-catalyst-header-bigtop/package.json
themes/gatsby-theme-catalyst-header-side/package.json
themes/gatsby-theme-catalyst-header-top/package.json
themes/gatsby-theme-catalyst-helium/package.json
themes/gatsby-theme-catalyst-hydrogen/package.json
themes/gatsby-theme-catalyst-sanity/package.json
www/package.json
yarn.lock

- the bug in Gatsby with mismatched Theme-UI versions that was affecting Catalyst has been fixed.
- Closes #650

(all): unpin Gatsby versions

---

themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul.js

- better aria roles for nav menus

(header): improve aria roles on navigation menus

---

starters/gatsby-starter-catalyst-helium/content/posts/5-tips-for-space-travel-success.mdx
starters/gatsby-starter-catalyst-helium/content/posts/draft-post.mdx
starters/gatsby-starter-catalyst-helium/content/posts/how-we-will-one-day-colonize-the-sun.mdx
starters/gatsby-starter-catalyst-helium/content/posts/how-you-should-pack-for-space-travel.mdx
starters/gatsby-starter-catalyst-helium/content/posts/rocket-ship-design-for-beginners.mdx
starters/gatsby-starter-catalyst-helium/content/posts/space-is-not-the-final-frontier.mdx
starters/gatsby-starter-catalyst-helium/content/posts/the-food-you-will-like-best-in-space.mdx
starters/gatsby-starter-catalyst-helium/content/posts/what-to-do-when-things-go-wrong-during-a-rocket-launch.mdx
starters/gatsby-starter-catalyst-helium/content/posts/who-you-choose-to-go-to-space-says-a-lot-about-you.mdx
themes/gatsby-theme-catalyst-blog/README.md
themes/gatsby-theme-catalyst-blog/gatsby-node.js
themes/gatsby-theme-catalyst-helium/README.md
themes/gatsby-theme-catalyst-helium/src/components/post.js
themes/gatsby-theme-catalyst-helium/src/gatsby-theme-catalyst-blog/components/queries/post-query.js
www/content/docs/docs/gatsby-theme-catalyst-blog.mdx
www/content/docs/docs/gatsby-theme-catalyst-helium.mdx

- adds support for `featuredImageCaption` in frontmatter
- added captions to `gatsby-theme-catalyst-helium`

(blog): add support for featuredImageCaption

---

starters/gatsby-starter-catalyst-helium/gatsby-config.js
themes/gatsby-theme-catalyst-core/README.md
themes/gatsby-theme-catalyst-helium/README.md
themes/gatsby-theme-catalyst-helium/gatsby-config.js
www/content/docs/docs/gatsby-theme-catalyst-helium.mdx

- adds support for remarkImagesWidth option
- sets default size of images to 1920px in the starter

(helium): Updated support for remarkImagesWidth

---

themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/navbar/nav.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav.js

- fixes some errors in previous PR
- moves aria-haspopup to the correct location

(headers): Updated a11y in nav components

---

themes/gatsby-theme-catalyst-helium/src/components/post.js
themes/gatsby-theme-catalyst-lithium/src/components/post.js

- adds support for featuredImageCaption

(lithium): add featuredImageCaption

---

starters/gatsby-starter-catalyst-blog/package.json
starters/gatsby-starter-catalyst-core/package.json
starters/gatsby-starter-catalyst-helium/package.json
starters/gatsby-starter-catalyst-hydrogen/package.json
starters/gatsby-starter-catalyst-lithium/package.json
starters/gatsby-starter-catalyst-sanity/package.json
starters/gatsby-starter-catalyst/package.json
themes/gatsby-theme-catalyst-blog/package.json
themes/gatsby-theme-catalyst-core/package.json
themes/gatsby-theme-catalyst-footer/package.json
themes/gatsby-theme-catalyst-header-bigtop/package.json
themes/gatsby-theme-catalyst-header-side/package.json
themes/gatsby-theme-catalyst-header-top/package.json
themes/gatsby-theme-catalyst-helium/package.json
themes/gatsby-theme-catalyst-hydrogen/package.json
themes/gatsby-theme-catalyst-lithium/package.json
themes/gatsby-theme-catalyst-sanity/package.json
www/package.json
yarn.lock

- Updated gatsby versions due to https://github.com/gatsbyjs/gatsby/issues/25478#issuecomment-653207216

(core): update gatsby version

---

CHANGELOG.md
starters/gatsby-starter-catalyst-sanity/sanity-studio/package.json
starters/gatsby-starter-catalyst-sanity/sanity-studio/sanity.json
starters/gatsby-starter-catalyst-sanity/sanity-studio/schemas/blockContent.js
starters/gatsby-starter-catalyst-sanity/sanity-studio/schemas/page.js
starters/gatsby-starter-catalyst-sanity/sanity-studio/schemas/post.js
starters/gatsby-starter-catalyst-sanity/sanity-studio/schemas/project.js
starters/gatsby-starter-catalyst-sanity/sanity-studio/yarn.lock
themes/gatsby-theme-catalyst-sanity/README.md
themes/gatsby-theme-catalyst-sanity/gatsby-node.js
themes/gatsby-theme-catalyst-sanity/src/components/queries/post-list-query.js
themes/gatsby-theme-catalyst-sanity/src/components/queries/project-list-query.js
themes/gatsby-theme-catalyst-sanity/src/components/sanity/code.js
themes/gatsby-theme-catalyst-sanity/src/components/sanity/serializers.js
themes/gatsby-theme-catalyst-sanity/src/components/templates/post-list-template.js
themes/gatsby-theme-catalyst-sanity/src/components/templates/project-list-template.js
www/content/docs/docs/gatsby-theme-catalyst-sanity.mdx

- add code highlighting
- adds automatic excerpt creation
- adds reading time
- removes unnecessary items in studio

(sanity): update sanity core theme

---

themes/gatsby-theme-catalyst-sanity/gatsby-node.js
themes/gatsby-theme-catalyst-sanity/src/components/queries/category-list-query.js
themes/gatsby-theme-catalyst-sanity/src/components/templates/category-list-template.js

- when category pages are generated it will now also generate a list of all categories at sitename.com/categories/

(sanity): add category list page

---

starters/gatsby-starter-catalyst-bery/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-catalyst-bery/src/components/post-list-template.js
themes/gatsby-theme-catalyst-bery/src/gatsby-theme-catalyst-sanity/components/queries/post-list-query.js

- adds the ability to filter posts by category
- UI is not finished but functionality is there

(bery): filter posts by category

---

themes/gatsby-theme-catalyst-sanity/src/components/queries/category-query.js
themes/gatsby-theme-catalyst-sanity/src/components/templates/category-template.js

- fixes an error in the category template
- fixes #860

(sanity): fix missing excerpt, missing key

---

themes/gatsby-theme-catalyst-bery/src/components/post-template.js
themes/gatsby-theme-catalyst-bery/src/gatsby-theme-catalyst-sanity/components/queries/post-query.js
themes/gatsby-theme-catalyst-sanity/src/gatsby-theme-catalyst-core/utils/seo.js

- allows use of featured images/social images in the image prop of the SEO component

(sanity): Better support for image prop in SEO SANITY

---

themes/gatsby-theme-catalyst-core/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-dropdown-button.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-gatsbylink.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-left.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-right.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul-submenu.js

- Dropdown menus are activated on click now instead of on hover

(header-top): add clickable dropdown support

---

themes/gatsby-theme-catalyst-core/gatsby-node.js

- adds graphql type definitions to handle if the socialLinks array is null or empty

(core): add graphql type definition for social links

---

themes/gatsby-theme-catalyst-bery/package.json
yarn.lock

Missed these packages when going through previously

(bery): update framer-motion and gatsby-plugin-feed

---

starters/gatsby-starter-catalyst/content/pages/left-link.mdx
starters/gatsby-starter-catalyst/gatsby-config.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-mobile-button.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav.js

- Improves focus handling for mobile menu

(header-top): improve a11y focus handling for mobile menu

---

starters/gatsby-starter-catalyst-lithium/package.json
starters/gatsby-starter-catalyst-lithium/src/gatsby-plugin-theme-ui/index.js
yarn.lock

- changes from typeface-quando to fontsource-quando
The [fontsource project](https://github.com/fontsource/fontsource) appears to be more well maintained and future focused than the typeface project and I want to support their growing efforts.

(lithium): switch to fontsource quando

---

starters/gatsby-starter-catalyst-bery/sanity-studio/package.json
starters/gatsby-starter-catalyst-bery/sanity-studio/structure/deskStructure.js
starters/gatsby-starter-catalyst-bery/sanity-studio/yarn.lock
starters/gatsby-starter-catalyst-hydrogen/sanity-studio/package.json
starters/gatsby-starter-catalyst-hydrogen/sanity-studio/structure/deskStructure.js
starters/gatsby-starter-catalyst-hydrogen/sanity-studio/yarn.lock
starters/gatsby-starter-catalyst-sanity/sanity-studio/package.json
starters/gatsby-starter-catalyst-sanity/sanity-studio/structure/deskStructure.js
starters/gatsby-starter-catalyst-sanity/sanity-studio/yarn.lock
yarn.lock

- updates SANITY studio versions for `bery`, `sanity` and `hydrogen`

(sanity): update SANITY studio versions

---

starters/gatsby-starter-catalyst-blog/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-catalyst-header-side/src/components/branding/branding.js
themes/gatsby-theme-catalyst-header-side/src/components/header.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-icons.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-li-submenu.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-li.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-dropdown-button.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-mobile-button.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-ul-submenu.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav.js
www/content/docs/404.mdx
www/content/docs/docs.mdx
www/gatsby-config.js
www/src/components/features.js
www/src/components/hero.js
www/src/gatsby-plugin-theme-ui/index.js
www/src/pages/index.js

- Updates the functionality for the sidebar header to default to buttons 
- Some style updates to the docs site

(header-side): refactor to buttons for dropdowns, update docs

---

starters/gatsby-starter-catalyst-blog/src/gatsby-plugin-theme-ui/index.js
www/content/docs/docs.mdx
www/package.json
www/src/components/animated-blocks.js
www/src/components/hero.js
www/src/gatsby-plugin-theme-ui/index.js
www/src/pages/index.js

- adds star button
- Improves readability of the How it works section

(www): update landing page

---

themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-dropdown-button.js
themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links.js

- allows for multiple dropdowns to be open at once by switching how the link behaviour is handled

(header-side): allow multiple drop downs open at once

---

sanity-templates/sanity-template-catalyst/template/web/gatsby-config.js
starters/gatsby-starter-catalyst-bery/gatsby-config.js
starters/gatsby-starter-catalyst-blog/gatsby-config.js
starters/gatsby-starter-catalyst-core/gatsby-config.js
starters/gatsby-starter-catalyst-sanity/gatsby-config.js
starters/gatsby-starter-catalyst/gatsby-config.js
themes/gatsby-theme-catalyst-bery/gatsby-config.js
themes/gatsby-theme-catalyst-core/README.md
themes/gatsby-theme-catalyst-helium/gatsby-config.js
themes/gatsby-theme-catalyst-hydrogen/gatsby-config.js
themes/gatsby-theme-catalyst-lithium/gatsby-config.js
www/content/docs/docs/gatsby-theme-catalyst-core.mdx
www/content/docs/docs/gatsby-theme-catalyst-helium.mdx
www/content/docs/docs/gatsby-theme-catalyst-lithium.mdx
www/content/docs/docs/getting-started.mdx

- finishes the process of implementing options for `imageQuality`

(all): finish implementing image quality

---

.github/workflows/publish-gatsby-starter-catalyst-bery.yml
.github/workflows/publish-gatsby-starter-catalyst-blog.yml
.github/workflows/publish-gatsby-starter-catalyst-core.yml
.github/workflows/publish-gatsby-starter-catalyst-helium.yml
.github/workflows/publish-gatsby-starter-catalyst-hydrogen.yml
.github/workflows/publish-gatsby-starter-catalyst-lithium.yml
.github/workflows/publish-gatsby-starter-catalyst-sanity.yml
.github/workflows/publish-gatsby-starter-catalyst-stripe.yml
.github/workflows/publish-gatsby-starter-catalyst.yml
starters/gatsby-starter-catalyst-bery/package.json
starters/gatsby-starter-catalyst-blog/package.json
starters/gatsby-starter-catalyst-core/package.json
starters/gatsby-starter-catalyst-helium/package.json
starters/gatsby-starter-catalyst-hydrogen/package.json
starters/gatsby-starter-catalyst-lithium/package.json
starters/gatsby-starter-catalyst-sanity/package.json
starters/gatsby-starter-catalyst-stripe/package.json
starters/gatsby-starter-catalyst/package.json

- break all of the publish workflows out into their own seperate streams.

(gh): individual publish workflows for the starters

---

sanity-templates/sanity-template-bery/template/web/package.json
sanity-templates/sanity-template-bery/template/web/src/gatsby-plugin-theme-ui/index.js
starters/gatsby-starter-catalyst-bery/package.json
starters/gatsby-starter-catalyst-bery/src/gatsby-plugin-theme-ui/index.js
starters/gatsby-starter-catalyst-lithium/gatsby-config.js
starters/gatsby-starter-catalyst-lithium/package.json
starters/gatsby-starter-catalyst-lithium/src/gatsby-plugin-theme-ui/index.js
yarn.lock

- update to the latest fontsource versions

(bery/lithium): update font sourcing

---

.changeset/config.json
.changeset/pre.json
.github/workflows/release.yml
package.json
yarn.lock

- adds changesets to the repo to manage changelogs

(all): initial setup of changesets

---

CONTRIBUTING.md
www/content/docs/docs/contribution.mdx

- adds some more detail on contributing and repo setup

(docs): update contribution docs

---

.changeset/big-flies-think.md
.changeset/config.json
sanity-templates/sanity-template-catalyst/template/web/src/components/header/branding.js
starters/gatsby-starter-catalyst-blog/src/components/header/branding.js
starters/gatsby-starter-catalyst-lithium/src/components/header/branding.js
starters/gatsby-starter-catalyst-sanity/src/components/header/branding.js
starters/gatsby-starter-catalyst/src/components/header/branding.js
www/src/components/header/branding.js

See https://github.com/gatsbyjs/gatsby/issues/31031

(fix): remove loading=eager due to but in gatsby-plugin-image

---

.changeset/mighty-zoos-do.md
.github/workflows/release.yml
lerna.json
package.json
sanity-templates/sanity-template-bery/template/web/package.json
sanity-templates/sanity-template-catalyst/template/web/package.json
starters/gatsby-starter-catalyst-bery/package.json
starters/gatsby-starter-catalyst-blog/package.json
starters/gatsby-starter-catalyst-core/package.json
starters/gatsby-starter-catalyst-helium/package.json
starters/gatsby-starter-catalyst-hydrogen/package.json
starters/gatsby-starter-catalyst-lithium/package.json
starters/gatsby-starter-catalyst-sanity/package.json
starters/gatsby-starter-catalyst-stripe/package.json
starters/gatsby-starter-catalyst/package.json
themes/gatsby-theme-catalyst-bery/package.json
themes/gatsby-theme-catalyst-blog/package.json
themes/gatsby-theme-catalyst-core/package.json
themes/gatsby-theme-catalyst-footer/package.json
themes/gatsby-theme-catalyst-header-bigtop/package.json
themes/gatsby-theme-catalyst-header-side/package.json
themes/gatsby-theme-catalyst-header-top/package.json
themes/gatsby-theme-catalyst-helium/package.json
themes/gatsby-theme-catalyst-hydrogen/package.json
themes/gatsby-theme-catalyst-lithium/package.json
themes/gatsby-theme-catalyst-sanity/package.json
themes/gatsby-theme-catalyst-stripe/package.json
www/package.json
yarn.lock

- updates to gatsby v3.5
- remove Lerna as this functionality is now covered by Changesets

(deps): update gatsby 3.5, remove lerna

---

.changeset/honest-rabbits-cheer.md
starters/gatsby-starter-catalyst-hydrogen/src/components/header/branding.js
themes/gatsby-theme-catalyst-hydrogen/src/components/home-page/home-card.js

- fixes font size on the cards used on the homepage
- A few other very small visual improvements to the cards, e.g. box-shadow

(hydrogen): update font size on card, other visual improvements

---

.changeset/ten-bottles-carry.md
themes/gatsby-theme-catalyst-hydrogen/src/components/home-page/home-card.js

- very minor tweaks to styling of the work card; explicit header size and hover colors

(hydrogen): updates to work card

---

.changeset/large-owls-sin.md
themes/gatsby-theme-catalyst-sanity/src/components/sanity/use-site-metadata.js

- fixes a bug where missing social links data from SANITY would cause a build to fail

(sanity): fix use site meta data

---

.changeset/bright-wasps-bow.md
starters/gatsby-starter-catalyst-hydrogen/src/components/header/branding.js
starters/gatsby-starter-catalyst-lithium/src/components/header/branding.js
starters/gatsby-starter-catalyst-sanity/src/components/header/branding.js
starters/gatsby-starter-catalyst/src/components/header/branding.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/nav-menu.js
themes/gatsby-theme-catalyst-header-top/src/components/branding.js
themes/gatsby-theme-catalyst-header-top/src/components/nav-menu-left.js
themes/gatsby-theme-catalyst-header-top/src/components/nav-menu-right.js
themes/gatsby-theme-catalyst-header-top/src/components/social-icons.js

- adjusts how spacing is handled around menu items to ensure they are visually consistent when there are no social links added to the site.

(header): adjust default spacing around menu items

---

.changeset/clean-tools-search.md
themes/gatsby-theme-catalyst-sanity/src/components/sanity/serializers.js

-Fixes missing serializer types

(sanity): add missing ul, ol, and li to sanity serializers

---

.changeset/hot-ties-greet.md
.github/workflows/test-header-bigtop.yml
.github/workflows/test-header-side.yml
.github/workflows/test-header-top.yml
themes/gatsby-theme-catalyst-header-bigtop/src/components/dropdown-button.js
themes/gatsby-theme-catalyst-header-bigtop/src/components/hamburger-button.js
themes/gatsby-theme-catalyst-header-side/src/components/dropdown-button.js
themes/gatsby-theme-catalyst-header-side/src/components/hamburger-button.js
themes/gatsby-theme-catalyst-header-top/src/components/dropdown-button.js
themes/gatsby-theme-catalyst-header-top/src/components/hamburger-button.js

- adds missing aria-expanded property to the dropdown buttons and hamburger button
- adds tests just for the headers

(headers): add aria expanded property

---

.changeset/tiny-pumas-teach.md
sanity-templates/sanity-template-bery/template/web/package.json
sanity-templates/sanity-template-catalyst/template/web/package.json
starters/gatsby-starter-catalyst-bery/package.json
starters/gatsby-starter-catalyst-blog/package.json
starters/gatsby-starter-catalyst-core/package.json
starters/gatsby-starter-catalyst-helium/package.json
starters/gatsby-starter-catalyst-hydrogen/package.json
starters/gatsby-starter-catalyst-lithium/package.json
starters/gatsby-starter-catalyst-sanity/package.json
starters/gatsby-starter-catalyst-stripe/package.json
starters/gatsby-starter-catalyst/package.json
www/package.json
yarn.lock

- Updates prettier dependencies to all ber on a unified version

(chore): update prettier deps
