ehowey/gatsby-theme-catalyst

themes/gatsby-theme-catalyst-blog/gatsby-node.js
themes/gatsby-theme-catalyst-blog/src/components/post-list.js
themes/gatsby-theme-catalyst-blog/src/components/post.js
themes/gatsby-theme-catalyst-blog/src/templates/post-query.js
themes/gatsby-theme-catalyst-blog/src/templates/posts-query.js

- Added in timeToRead using [gatsby-remark-reading-time](https://www.gatsbyjs.org/packages/gatsby-remark-reading-time/)
- Updated posts query to use `nodes` instead of `edges->node`. If you were shadowing this may be breaking, all you would need to do is update your shadowed component.

(catalyst blog): Add timeToRead

---

themes/gatsby-theme-catalyst-header-side/src/components/navbar/nav-links-anchorlink.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-anchorlink.js

- Fixes a bug where you needed to press the back button a lot on a single page use of these themes. hashSpy was updating the browser history.

(all): Remove hashSpy on achor links

---

themes/gatsby-theme-catalyst-blog/gatsby-node.js

- Fixes an error if the timeToRead field returns null

(catalyst-blog): allow timeToRead to be null

---

themes/gatsby-theme-catalyst-hydrogen/README.md
themes/gatsby-theme-catalyst-hydrogen/gatsby-config.js
themes/gatsby-theme-catalyst-sanity/README.md

- adds the ability to pass down core theme options directly from `gatsby-theme-catalyst-hydrogen` to `gatsby-theme-catalyst-core`

(hydrogen): add ability to pass down core theme options

---

themes/gatsby-theme-catalyst-core/gatsby-config.js
themes/gatsby-theme-catalyst-core/gatsby-node.js
themes/gatsby-theme-catalyst-core/src/utils/default-options.js

- Modifications to `gatsby-node.js` and `gatsby-config.js` to ensure that the content path and asset path are properly created if they are not there already.  Prevents edge case problems when someone installs the theme on a non-Catalyst starter.

(core): ensure file folders are created for contentPath and assetPath

---

themes/gatsby-theme-catalyst-helium/README.md
themes/gatsby-theme-catalyst-hydrogen/README.md
themes/gatsby-theme-catalyst-lithium/README.md
themes/gatsby-theme-catalyst-sanity/README.md

Links inside themes to the documentation were broken, so I fixed them. Also the documentation for lithium had inconsistent formatting to the others and was missing the link to the documentation, so I added those too.

Fix broken links in theme documentation and make formatting consistent.

---

themes/gatsby-theme-catalyst-blog/README.md
themes/gatsby-theme-catalyst-helium/README.md
themes/gatsby-theme-catalyst-helium/gatsby-config.js
themes/gatsby-theme-catalyst-lithium/README.md
themes/gatsby-theme-catalyst-lithium/gatsby-config.js
www/content/docs/docs/gatsby-theme-catalyst-helium.mdx
www/content/docs/docs/gatsby-theme-catalyst-lithium.mdx

- added missing option field for the `rssTitle`
- added some better documentation for this feature

(docs + lithium + helium): add rssTitle option, add documentation

---

.github/workflows/test-themes.yml
cypress/e2e/themes.test.js
package.json
starters/gatsby-starter-catalyst-sanity/gatsby-config.js
themes/gatsby-theme-catalyst-helium/gatsby-config.js
themes/gatsby-theme-catalyst-lithium/gatsby-config.js

- moves `gatsby-plugin-feed` up to the `lithium` and `helium` themes
- addresses #727 temporarily, not the most elegant solution but it works
- improved tests so it doesn't occasionally fail
- added test for lithium

(lithium, helium): add feed plugin to gatsby-config

---

CHANGELOG.md
starters/gatsby-starter-catalyst-blog/src/gatsby-plugin-theme-ui/index.js
starters/gatsby-starter-catalyst-helium/src/gatsby-plugin-theme-ui/index.js
starters/gatsby-starter-catalyst-sanity/src/gatsby-plugin-theme-ui/index.js
starters/gatsby-starter-catalyst/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-catalyst-core/src/gatsby-plugin-theme-ui/index.js
www/content/docs/docs/migrating.mdx
www/content/docs/docs/theme-ui.mdx

- **Breaking**: Removes default dark mode from `baseTheme` which is exported from `gatsby-theme-catalyst-core`. This was making it difficult to disable dark mode.  It also makes it more visually obvious how to change colors in the starters.  For more about changes and migrating see the CHANGELOG.md

(core): remove default dark mode from base theme-ui spec

---

themes/gatsby-theme-catalyst-helium/src/components/post-list.js
themes/gatsby-theme-catalyst-helium/src/components/post.js
themes/gatsby-theme-catalyst-lithium/src/components/post.js

- fixes missing key, credit to @AlexHff
- adjusts padding at 1440px and above to look better on post lists for `helium`

(lithium, helium): missing key and adjusted padding

---

starters/gatsby-starter-catalyst-lithium/README.md

There was an error in command that create sample gatsby-starter-catalyst-lithium project. Added one character

Fix the link of the repo in catalyst-lithium README file

---

starters/gatsby-starter-catalyst-bery/sanity-studio/schemas/menuLink.js
starters/gatsby-starter-catalyst-hydrogen/sanity-studio/schemas/menuLink.js
starters/gatsby-starter-catalyst-sanity/sanity-studio/schemas/menuLink.js
starters/gatsby-starter-catalyst/gatsby-config.js
themes/gatsby-theme-catalyst-core/gatsby-node.js
themes/gatsby-theme-catalyst-core/src/utils/use-site-metadata.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-icons.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-left.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-right.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav.js
themes/gatsby-theme-catalyst-sanity/src/gatsby-theme-catalyst-core/utils/use-site-metadata.js

- adds support to `gatsby-theme-catalyst-header-top` for split links, e.g. links on the left and links on the right. The default is for the links to be stacked on the right. And will not affect any current behaviour.  If you are doing a lot of custom component shadowing on top of this theme you may need to revisit how you are component shadowing but that is an advanced use case.
- **BREAKING CHANGE**: This is a breaking change ONLY for SANITY.io based themes and will require you to update your `menuLinks.js` schema and redeploy the GraphQL schema,  I am sorry but there isn't a way in SANITY for me to easily control the GraphQL node creation and this will require an update.
- You can now specify a `location: "left"` or `location: "right"` in the menuLinks array in `gatsby-config.js`
- This …

(header-top): add support for split links with fallback for default

---

themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-left.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-links-right.js
themes/gatsby-theme-catalyst-header-top/src/components/navbar/nav-ul.js

In order to support both a left and right nav menu the structure included a splitter div in the middle separating the two lists. This should have been a ul element.

(header-top): switch div and ul tag order for correct semantic structure in links

---

CHANGELOG.md
themes/gatsby-theme-catalyst-core/gatsby-config.js
themes/gatsby-theme-catalyst-core/package.json
www/content/docs/docs/migrating.mdx
yarn.lock

**Breaking Change**: Removed [gatsby-plugin-offline](https://www.gatsbyjs.com/plugins/gatsby-plugin-offline/) from the core theme as there are more considerations and impacts from service workers than should be included in the core theme. This plugin has a lot of power and I would suggest using it on most Gatsby sites but want to leave this as an optional addition versus a forced inclusion in the core theme. If you want to include this in your site you would just add it to your main `gatsby-config.js` file.

(core): remove gatsby-plugin-offline and add docs

---

themes/gatsby-theme-catalyst-core/gatsby-config.js

As identified by @wgx it is not easy to currently change the default image compression settings. This PR would introduce an `imageQuality` theme option that could be set on the core theme and would affect all images generated by `gatsby-plugin-sharp` and `gatsby-remark-images`.  
@wgx Is this what you are looking for?
Fixes: https://github.com/ehowey/gatsby-theme-catalyst/issues/1127

(core): add imageQuality theme option

---

starters/gatsby-starter-catalyst-sanity/gatsby-config.js
themes/gatsby-theme-catalyst-core/gatsby-node.js
themes/gatsby-theme-catalyst-core/src/utils/use-catalyst-config.js
themes/gatsby-theme-catalyst-sanity/README.md
themes/gatsby-theme-catalyst-sanity/gatsby-node.js
themes/gatsby-theme-catalyst-sanity/src/components/sanity/use-sanity-config.js
www/content/docs/docs/gatsby-theme-catalyst-sanity.mdx

Most theme values are added to the graphQL node. This removes sanityProjectId, sanityDataset, sanityToken, sanityOverlayDrafts, and sanityWatchmode from the configuration node for security purposes. This is not publicly available but I was concerned it could be exposed too easily and hence am removing those. You should only be using ENV variables for that data, especially the Token.
- all removes the long deprecated `mobileMenuBreakpoint` which I noticed was mistakenly left in.

(sanity): remove values from graphql nodes

---

sanity-templates/sanity-template-catalyst/template/web/gatsby-config.js
starters/gatsby-starter-catalyst-blog/gatsby-config.js
starters/gatsby-starter-catalyst-core/gatsby-config.js
starters/gatsby-starter-catalyst-sanity/gatsby-config.js
starters/gatsby-starter-catalyst/gatsby-config.js
themes/gatsby-theme-catalyst-bery/README.md
themes/gatsby-theme-catalyst-bery/gatsby-config.js
themes/gatsby-theme-catalyst-core/README.md
themes/gatsby-theme-catalyst-ecommerce/gatsby-config.js
themes/gatsby-theme-catalyst-helium/README.md
themes/gatsby-theme-catalyst-helium/gatsby-config.js
themes/gatsby-theme-catalyst-hydrogen/README.md
themes/gatsby-theme-catalyst-hydrogen/gatsby-config.js
themes/gatsby-theme-catalyst-lithium/README.md
themes/gatsby-theme-catalyst-lithium/gatsby-config.js
www/content/docs/docs/gatsby-theme-catalyst-bery.mdx
www/content/docs/docs/gatsby-theme-catalyst-core.mdx
www/content/docs/docs/gatsby-theme-catalyst-helium.mdx
www/content/docs/docs/gatsby-theme-catalyst-lithium.mdx
www/content/docs/docs/getting-started.mdx
www/content/docs/docs/theme-options.mdx
www/gatsby-config.js

There was mixed messaging with both `invertLogo` and `invertSiteLogo`. 
`invertSiteLogo` is correct and always has been - given this is a bit off an eccentric theme option I don't think anyone ran into this issue but I am fixing it.

(all): fix invertSiteLogo

---

themes/gatsby-theme-catalyst-sanity/gatsby-node.js
themes/gatsby-theme-catalyst-sanity/src/components/sanity/use-sanity-config.js

- I removed sanityProjectId and sanityDataset from the graphql config, this was a mistake. Added back in.

(sanity): fix missing graphql config options

---

themes/gatsby-theme-catalyst-core/gatsby-config.js

Mistakenly used `quality` instead of `defaultQuality`

(core): Fix incorrect to plugin option for gatsby-plugin-sharp

---

sanity-templates/sanity-template-bery/template/studio/schemas/post.js
starters/gatsby-starter-catalyst-bery/sanity-studio/schemas/post.js

- fixes broken date field which was causing the posts to all display with an "untitled" title in the SANITY studio despite appearing fine on the frontend.

(bery): fix post preview in SANITY studio
